---
- name: Install required packages
  dnf:
    name:
      - python3
      - python3-pip
      - git
    state: present

- name: Create application directory
  file:
    path: /opt/prometheus-exporter
    state: directory
    mode: '0755'

- name: Copy application files
  copy:
    src: "{{ item }}"
    dest: /opt/prometheus-exporter/
  with_items:
    - "app/app.py"
    - "app/requirements.txt"

# Включаем задачи в зависимости от выбранного типа развертывания
- include_tasks: vm_deploy.yml
  when: deployment_type == 'vm'

- include_tasks: container_deploy.yml
  when: deployment_type == 'container'